package Principal;

import Estrutura.ViewManutencaoPadrao;
import ViewCadastro.ViewManutencaoCor;
import ViewCadastro.ViewManutencaoEstado;
import ViewCadastro.ViewManutencaoFornecedor;
import ViewCadastro.ViewManutencaoGrupoFiscal;
import ViewCadastro.ViewManutencaoGrupoSubGrupo;
import ViewCadastro.ViewManutencaoMarca;
import ViewCadastro.ViewManutencaoMunicipio;
import ViewCadastro.ViewManutencaoNcmsh;
import ViewCadastro.ViewManutencaoPais;
import ViewCadastro.ViewManutencaoPessoa;
import ViewCadastro.ViewManutencaoProduto;
import ViewCadastro.ViewManutencaoTransportadora;
import ViewCadastro.ViewManutencaoUnidadeMedida;
import ViewCadastro.ViewManutencaoUsuario;
import ViewCadastro.ViewManutencaoVendedor;
import ViewFaturamento.ViewManutencaoCondicaoPagamento;
import ViewFaturamento.ViewManutencaoFormularioNotaFederal;
import ViewFaturamento.ViewManutencaoLancamento;
import ViewFaturamento.ViewManutencaoNotaEntrada;
import ViewFaturamento.ViewManutencaoPedidoCompleto;
import ViewFaturamento.ViewManutencaoTipoCobranca;
import ViewFaturamento.ViewManutencaoTipoLancamento;
import ViewFaturamento.ViewManutencaoTipoNota;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gelvazio Camargo
 */
public class FormularioPrincipal extends JFrame {

    public void Principal() {
        initComponents();
        JOptionPane.setRootFrame(this);
        setExtendedState(MAXIMIZED_BOTH);
        // setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Principal = new javax.swing.JDesktopPane();
        Menu_Principal = new javax.swing.JMenuBar();
        Menu_Cadastros = new javax.swing.JMenu();
        Menu_Pessoa = new javax.swing.JMenu();
        Cliente = new javax.swing.JMenuItem();
        Fornecedor = new javax.swing.JMenuItem();
        Vendedor = new javax.swing.JMenuItem();
        Transportadora = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        Menu_Produtp = new javax.swing.JMenu();
        Produto = new javax.swing.JMenuItem();
        grupoFiscal = new javax.swing.JMenuItem();
        MenuGrupo = new javax.swing.JMenuItem();
        MenuNCMSH = new javax.swing.JMenuItem();
        Unidade_Medida = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Regiao = new javax.swing.JMenuItem();
        Estado = new javax.swing.JMenuItem();
        Cidade = new javax.swing.JMenuItem();
        Menu_Faturamento = new javax.swing.JMenu();
        DAV = new javax.swing.JMenu();
        Pedido = new javax.swing.JMenuItem();
        Orçamento = new javax.swing.JMenuItem();
        Orçamento1 = new javax.swing.JMenuItem();
        Menu_Compras = new javax.swing.JMenu();
        Nota_Entrada = new javax.swing.JMenuItem();
        Ordem_de_Compras = new javax.swing.JMenuItem();
        Relatorio_Produtos_Solicitados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Nota_Fiscal = new javax.swing.JMenuItem();
        Cancela_Notas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        Menu_Financeiro = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        Baixa_Lançamentos = new javax.swing.JMenuItem();
        Menu_Boleto = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        Menu_Caixa = new javax.swing.JMenu();
        Abertura_Caixa = new javax.swing.JMenuItem();
        Fechamento_Caixa = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        Menu_Relatorios = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        Relatorio_Fornecedores = new javax.swing.JMenuItem();
        Relatorio_Transportadora = new javax.swing.JMenuItem();
        Relatorio_Vendedores = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Relatorio_Vendas = new javax.swing.JMenuItem();
        Relatorio_Compras = new javax.swing.JMenuItem();
        Relatorio_Contas_Pagar = new javax.swing.JMenuItem();
        Relatorio_Contas_Receber = new javax.swing.JMenuItem();
        Relatorios_Curva_ABC = new javax.swing.JMenuItem();
        Relatorio_de_Comissões = new javax.swing.JMenuItem();
        Relatorio_Notas = new javax.swing.JMenu();
        Relatorio_Notas_Entrada = new javax.swing.JMenuItem();
        Relatorio_Notas_Fiscais = new javax.swing.JMenuItem();
        Relatorio_DAV = new javax.swing.JMenu();
        Relatorio_Pedidos = new javax.swing.JMenuItem();
        Relatorio_Orcamento = new javax.swing.JMenuItem();
        Relatorio_Pre_Venda = new javax.swing.JMenuItem();
        Relatorio_Ordem_Serviço = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Relatorio_Região = new javax.swing.JMenuItem();
        Relatorio_Estados = new javax.swing.JMenuItem();
        Relatorio_Cidades = new javax.swing.JMenuItem();
        Relatorio_Produtos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Relatorio_Produtos_Vendidos = new javax.swing.JMenuItem();
        Menu_Config = new javax.swing.JMenu();
        Tipo_Notas = new javax.swing.JMenuItem();
        Grupo_Fiscal = new javax.swing.JMenuItem();
        NCMSH = new javax.swing.JMenuItem();
        MVA = new javax.swing.JMenuItem();
        Filial = new javax.swing.JMenuItem();
        Menu_Config1 = new javax.swing.JMenu();
        Tipo_Notas1 = new javax.swing.JMenuItem();
        Grupo_Fiscal1 = new javax.swing.JMenuItem();
        NCMSH1 = new javax.swing.JMenuItem();
        MVA1 = new javax.swing.JMenuItem();
        Filial1 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle Comercial");
        setAlwaysOnTop(true);

        Panel_Principal.setBackground(new java.awt.Color(51, 51, 255));
        Panel_Principal.setForeground(new java.awt.Color(153, 255, 153));
        Panel_Principal.setName(""); // NOI18N

        Menu_Principal.setFocusable(false);
        Menu_Principal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Menu_PrincipalMouseMoved(evt);
            }
        });

        Menu_Cadastros.setText("Cadastros");

        Menu_Pessoa.setText("Pessoa");
        Menu_Pessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_PessoaActionPerformed(evt);
            }
        });

        Cliente.setText("Cliente");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });
        Menu_Pessoa.add(Cliente);

        Fornecedor.setText("Fornecedor");
        Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FornecedorActionPerformed(evt);
            }
        });
        Menu_Pessoa.add(Fornecedor);

        Vendedor.setText("Vendedor");
        Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendedorActionPerformed(evt);
            }
        });
        Menu_Pessoa.add(Vendedor);

        Transportadora.setText("Transportadora");
        Transportadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransportadoraActionPerformed(evt);
            }
        });
        Menu_Pessoa.add(Transportadora);

        jMenuItem11.setText("Usuário");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        Menu_Pessoa.add(jMenuItem11);

        Menu_Cadastros.add(Menu_Pessoa);

        Menu_Produtp.setText("Produto");

        Produto.setText("Produto");
        Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoActionPerformed(evt);
            }
        });
        Menu_Produtp.add(Produto);

        grupoFiscal.setText("Grupo Fiscal");
        grupoFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoFiscalActionPerformed(evt);
            }
        });
        Menu_Produtp.add(grupoFiscal);

        MenuGrupo.setText("Grupo / Sub-Grupo ");
        MenuGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGrupoActionPerformed(evt);
            }
        });
        Menu_Produtp.add(MenuGrupo);

        MenuNCMSH.setText("NCMSH");
        MenuNCMSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNCMSHActionPerformed(evt);
            }
        });
        Menu_Produtp.add(MenuNCMSH);

        Unidade_Medida.setText("Unidade Medida");
        Unidade_Medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Unidade_MedidaActionPerformed(evt);
            }
        });
        Menu_Produtp.add(Unidade_Medida);

        jMenuItem15.setText("Marca");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        Menu_Produtp.add(jMenuItem15);

        jMenuItem7.setText("Cor");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Menu_Produtp.add(jMenuItem7);

        Menu_Cadastros.add(Menu_Produtp);

        jMenu3.setText("Pais / Estado / Municipio");

        Regiao.setText("País");
        Regiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegiaoActionPerformed(evt);
            }
        });
        jMenu3.add(Regiao);

        Estado.setText("Estado");
        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });
        jMenu3.add(Estado);

        Cidade.setText("Municipio");
        Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CidadeActionPerformed(evt);
            }
        });
        jMenu3.add(Cidade);

        Menu_Cadastros.add(jMenu3);

        Menu_Principal.add(Menu_Cadastros);

        Menu_Faturamento.setText("Faturamento");
        Menu_Faturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_FaturamentoActionPerformed(evt);
            }
        });

        DAV.setText("DAV");

        Pedido.setText("Pedido");
        Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoActionPerformed(evt);
            }
        });
        DAV.add(Pedido);

        Orçamento.setText("Orçamento");
        Orçamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrçamentoActionPerformed(evt);
            }
        });
        DAV.add(Orçamento);

        Orçamento1.setText("Pedido Completo");
        Orçamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Orçamento1ActionPerformed(evt);
            }
        });
        DAV.add(Orçamento1);

        Menu_Faturamento.add(DAV);

        Menu_Compras.setText("Compras");

        Nota_Entrada.setText("Nota Entrada");
        Nota_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nota_EntradaActionPerformed(evt);
            }
        });
        Menu_Compras.add(Nota_Entrada);

        Ordem_de_Compras.setText("Ordem de Compras");
        Ordem_de_Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ordem_de_ComprasActionPerformed(evt);
            }
        });
        Menu_Compras.add(Ordem_de_Compras);

        Relatorio_Produtos_Solicitados.setText("Relatorio Produtos Solicitados");
        Relatorio_Produtos_Solicitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Relatorio_Produtos_SolicitadosActionPerformed(evt);
            }
        });
        Menu_Compras.add(Relatorio_Produtos_Solicitados);

        Menu_Faturamento.add(Menu_Compras);

        jMenu2.setText("Notas");

        Nota_Fiscal.setText("Nota Fiscal Eletrônica");
        Nota_Fiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nota_FiscalActionPerformed(evt);
            }
        });
        jMenu2.add(Nota_Fiscal);

        Cancela_Notas.setText("Cancela Notas");
        Cancela_Notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancela_NotasActionPerformed(evt);
            }
        });
        jMenu2.add(Cancela_Notas);

        Menu_Faturamento.add(jMenu2);

        jMenu7.setText("Cadastros Faturamento");

        jMenuItem2.setText("Condição de Pagamento");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuItem13.setText("Tipo de Cobrança");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem13);

        jMenuItem16.setText("Tipo de Notas");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem16);

        Menu_Faturamento.add(jMenu7);

        Menu_Principal.add(Menu_Faturamento);

        Menu_Financeiro.setText("Financeiro");

        jMenuItem10.setText("Contas a Receber");
        Menu_Financeiro.add(jMenuItem10);

        jMenuItem12.setText("Contas a Pagar");
        Menu_Financeiro.add(jMenuItem12);

        Baixa_Lançamentos.setText("Baixa Lançamentos");
        Baixa_Lançamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Baixa_LançamentosActionPerformed(evt);
            }
        });
        Menu_Financeiro.add(Baixa_Lançamentos);

        Menu_Boleto.setText("Boleto Bancario");

        jMenuItem26.setText("Implementar !!");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        Menu_Boleto.add(jMenuItem26);

        Menu_Financeiro.add(Menu_Boleto);

        Menu_Caixa.setText("Caixa");

        Abertura_Caixa.setText("Abertura Caixa");
        Abertura_Caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Abertura_CaixaActionPerformed(evt);
            }
        });
        Menu_Caixa.add(Abertura_Caixa);

        Fechamento_Caixa.setText("Fechamento Caixa");
        Fechamento_Caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fechamento_CaixaActionPerformed(evt);
            }
        });
        Menu_Caixa.add(Fechamento_Caixa);

        Menu_Financeiro.add(Menu_Caixa);

        jMenuItem20.setText("Tipo Lancamento");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        Menu_Financeiro.add(jMenuItem20);

        jMenuItem21.setText("Lancamento");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        Menu_Financeiro.add(jMenuItem21);

        Menu_Principal.add(Menu_Financeiro);

        Menu_Relatorios.setText("Relatorios");

        jMenu5.setText("Pessoa");

        jMenuItem3.setText("Relatorio Clientes");
        jMenu5.add(jMenuItem3);

        Relatorio_Fornecedores.setText("Relatorio Fornecedores");
        Relatorio_Fornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Relatorio_FornecedoresActionPerformed(evt);
            }
        });
        jMenu5.add(Relatorio_Fornecedores);

        Relatorio_Transportadora.setText("Relatorio Transportadora");
        jMenu5.add(Relatorio_Transportadora);

        Relatorio_Vendedores.setText("Relatorio Vendedores");
        jMenu5.add(Relatorio_Vendedores);

        Menu_Relatorios.add(jMenu5);

        jMenu6.setText("Financeiro");

        Relatorio_Vendas.setText("Relatorio Vendas");
        jMenu6.add(Relatorio_Vendas);

        Relatorio_Compras.setText("Relatorio Compras");
        jMenu6.add(Relatorio_Compras);

        Relatorio_Contas_Pagar.setText("Relatorio Contas a Pagar");
        Relatorio_Contas_Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Relatorio_Contas_PagarActionPerformed(evt);
            }
        });
        jMenu6.add(Relatorio_Contas_Pagar);

        Relatorio_Contas_Receber.setText("Relatorio Contas a Receber");
        jMenu6.add(Relatorio_Contas_Receber);

        Relatorios_Curva_ABC.setText("Relatorio Curva ABC");
        jMenu6.add(Relatorios_Curva_ABC);

        Relatorio_de_Comissões.setText("Relatorio de Comissões");
        jMenu6.add(Relatorio_de_Comissões);

        Menu_Relatorios.add(jMenu6);

        Relatorio_Notas.setText("Notas");

        Relatorio_Notas_Entrada.setText("Relatorio Notas Entrada");
        Relatorio_Notas.add(Relatorio_Notas_Entrada);

        Relatorio_Notas_Fiscais.setText("Relatorio Notas Fiscais");
        Relatorio_Notas.add(Relatorio_Notas_Fiscais);

        Menu_Relatorios.add(Relatorio_Notas);

        Relatorio_DAV.setText("DAV");

        Relatorio_Pedidos.setText("Relatorio Pedidos");
        Relatorio_DAV.add(Relatorio_Pedidos);

        Relatorio_Orcamento.setText("Relatorio Orcamento");
        Relatorio_DAV.add(Relatorio_Orcamento);

        Relatorio_Pre_Venda.setText("Relatorio Pre_Venda");
        Relatorio_Pre_Venda.setName(""); // NOI18N
        Relatorio_DAV.add(Relatorio_Pre_Venda);

        Relatorio_Ordem_Serviço.setText("Relatorio Ordem Serviço");
        Relatorio_DAV.add(Relatorio_Ordem_Serviço);

        Menu_Relatorios.add(Relatorio_DAV);

        jMenu1.setText("Estado / Região / Cidade");

        Relatorio_Região.setText("Relatorio Região");
        jMenu1.add(Relatorio_Região);

        Relatorio_Estados.setText("Relatorio de Estados");
        jMenu1.add(Relatorio_Estados);

        Relatorio_Cidades.setText("Relatorio de Cidades");
        Relatorio_Cidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Relatorio_CidadesActionPerformed(evt);
            }
        });
        jMenu1.add(Relatorio_Cidades);

        Menu_Relatorios.add(jMenu1);

        Relatorio_Produtos.setText("Produtos");

        jMenuItem1.setText("Relatorio Produtos-Estoque");
        Relatorio_Produtos.add(jMenuItem1);

        jMenuItem4.setText("Relatorio Produtos Comprados");
        Relatorio_Produtos.add(jMenuItem4);

        Relatorio_Produtos_Vendidos.setText("Relatorio Produtos Vendidos");
        Relatorio_Produtos_Vendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Relatorio_Produtos_VendidosActionPerformed(evt);
            }
        });
        Relatorio_Produtos.add(Relatorio_Produtos_Vendidos);

        Menu_Relatorios.add(Relatorio_Produtos);

        Menu_Principal.add(Menu_Relatorios);

        Menu_Config.setText("Configuração");

        Tipo_Notas.setText("Tipo de Notas");
        Tipo_Notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipo_NotasActionPerformed(evt);
            }
        });
        Menu_Config.add(Tipo_Notas);

        Grupo_Fiscal.setText("Grupo Fiscal");
        Menu_Config.add(Grupo_Fiscal);

        NCMSH.setText("NCMSH");
        Menu_Config.add(NCMSH);

        MVA.setText("MVA");
        Menu_Config.add(MVA);

        Filial.setText("Filial");
        Menu_Config.add(Filial);

        Menu_Config1.setText("Configuração");

        Tipo_Notas1.setText("Tipo de Notas");
        Tipo_Notas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipo_Notas1ActionPerformed(evt);
            }
        });
        Menu_Config1.add(Tipo_Notas1);

        Grupo_Fiscal1.setText("Grupo Fiscal");
        Menu_Config1.add(Grupo_Fiscal1);

        NCMSH1.setText("NCMSH");
        Menu_Config1.add(NCMSH1);

        MVA1.setText("MVA");
        Menu_Config1.add(MVA1);

        Filial1.setText("Filial");
        Menu_Config1.add(Filial1);

        Menu_Config.add(Menu_Config1);

        Menu_Principal.add(Menu_Config);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuSairMousePressed(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        Menu_Principal.add(menuSair);

        setJMenuBar(Menu_Principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void Abertura_CaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Abertura_CaixaActionPerformed

	}//GEN-LAST:event_Abertura_CaixaActionPerformed

	private void Fechamento_CaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fechamento_CaixaActionPerformed

	}//GEN-LAST:event_Fechamento_CaixaActionPerformed

	private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed

	}//GEN-LAST:event_jMenuItem26ActionPerformed

	private void Ordem_de_ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ordem_de_ComprasActionPerformed

	}//GEN-LAST:event_Ordem_de_ComprasActionPerformed

	private void Relatorio_Produtos_SolicitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Relatorio_Produtos_SolicitadosActionPerformed

	}//GEN-LAST:event_Relatorio_Produtos_SolicitadosActionPerformed

	private void Menu_FaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_FaturamentoActionPerformed

	}//GEN-LAST:event_Menu_FaturamentoActionPerformed

    private void Menu_PrincipalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_PrincipalMouseMoved
        
    }//GEN-LAST:event_Menu_PrincipalMouseMoved

    private void FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FornecedorActionPerformed
        ViewManutencaoFornecedor formulario = new ViewManutencaoFornecedor();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_FornecedorActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        ViewManutencaoEstado formulario = new ViewManutencaoEstado();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_EstadoActionPerformed

    private void CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CidadeActionPerformed
        ViewManutencaoMunicipio formulario = new ViewManutencaoMunicipio();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_CidadeActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        ViewManutencaoPessoa formulario = new ViewManutencaoPessoa();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_ClienteActionPerformed

    private void VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendedorActionPerformed
        ViewManutencaoVendedor formulario = new ViewManutencaoVendedor();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_VendedorActionPerformed

    private void TransportadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransportadoraActionPerformed
        ViewManutencaoTransportadora formulario = new ViewManutencaoTransportadora();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_TransportadoraActionPerformed

    private void Menu_PessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_PessoaActionPerformed
        
    }//GEN-LAST:event_Menu_PessoaActionPerformed

    private void ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoActionPerformed
        ViewManutencaoProduto formulario = new ViewManutencaoProduto();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_ProdutoActionPerformed

    private void Cancela_NotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancela_NotasActionPerformed
        
    }//GEN-LAST:event_Cancela_NotasActionPerformed

    private void Relatorio_CidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Relatorio_CidadesActionPerformed
        
    }//GEN-LAST:event_Relatorio_CidadesActionPerformed

    private void Relatorio_FornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Relatorio_FornecedoresActionPerformed
        
    }//GEN-LAST:event_Relatorio_FornecedoresActionPerformed

    private void Relatorio_Contas_PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Relatorio_Contas_PagarActionPerformed
        
    }//GEN-LAST:event_Relatorio_Contas_PagarActionPerformed

    private void Relatorio_Produtos_VendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Relatorio_Produtos_VendidosActionPerformed
        
    }//GEN-LAST:event_Relatorio_Produtos_VendidosActionPerformed

    private void Unidade_MedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Unidade_MedidaActionPerformed
        ViewManutencaoUnidadeMedida formulario = new ViewManutencaoUnidadeMedida();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_Unidade_MedidaActionPerformed

    private void PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoActionPerformed
        ViewManutencaoPedidoCompleto formulario = new ViewManutencaoPedidoCompleto();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_PedidoActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        ViewManutencaoUsuario formulario = new ViewManutencaoUsuario();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void RegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegiaoActionPerformed
        ViewManutencaoPais formulario = new ViewManutencaoPais();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_RegiaoActionPerformed

    private void Baixa_LançamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Baixa_LançamentosActionPerformed
        
    }//GEN-LAST:event_Baixa_LançamentosActionPerformed

    private void grupoFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoFiscalActionPerformed
        ViewManutencaoGrupoFiscal formulario = new ViewManutencaoGrupoFiscal();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_grupoFiscalActionPerformed

    private void Nota_FiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nota_FiscalActionPerformed
        ViewManutencaoFormularioNotaFederal formulario = new ViewManutencaoFormularioNotaFederal();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_Nota_FiscalActionPerformed

    private void MenuNCMSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNCMSHActionPerformed
        ViewManutencaoNcmsh formulario = new ViewManutencaoNcmsh();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_MenuNCMSHActionPerformed

    private void MenuGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGrupoActionPerformed
        ViewManutencaoGrupoSubGrupo formulario = new ViewManutencaoGrupoSubGrupo();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_MenuGrupoActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ViewManutencaoCor formulario = new ViewManutencaoCor();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void Tipo_NotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipo_NotasActionPerformed
        ViewManutencaoTipoNota formulario = new ViewManutencaoTipoNota();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_Tipo_NotasActionPerformed

    private void OrçamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrçamentoActionPerformed
        ViewManutencaoPedidoCompleto formulario = new ViewManutencaoPedidoCompleto();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_OrçamentoActionPerformed

    private void Orçamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Orçamento1ActionPerformed
        ViewManutencaoPedidoCompleto formulario = new ViewManutencaoPedidoCompleto();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_Orçamento1ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        ViewManutencaoTipoCobranca formulario = new ViewManutencaoTipoCobranca();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ViewManutencaoCondicaoPagamento formulario = new ViewManutencaoCondicaoPagamento();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        ViewManutencaoMarca formulario = new ViewManutencaoMarca();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        ViewManutencaoTipoNota formulario = new ViewManutencaoTipoNota();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void Nota_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nota_EntradaActionPerformed
        ViewManutencaoNotaEntrada formulario = new ViewManutencaoNotaEntrada();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_Nota_EntradaActionPerformed

    private void Tipo_Notas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipo_Notas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tipo_Notas1ActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuSairMouseClicked

    private void menuSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMousePressed
        System.exit(0);
    }//GEN-LAST:event_menuSairMousePressed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        ViewManutencaoTipoLancamento formulario = new ViewManutencaoTipoLancamento();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        ViewManutencaoLancamento formulario = new ViewManutencaoLancamento();
        setaConfiguracaoFormulario(formulario);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    protected void setaConfiguracaoFormulario(ViewManutencaoPadrao formulario) {
        Panel_Principal.add(formulario);
        formulario.setClosable(true);
        formulario.setIconifiable(true);
        formulario.setResizable(true);
        formulario.setMaximizable(true);
        formulario.setVisible(true);
    }
    
    public void entrasistema() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Principal();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Abertura_Caixa;
    private javax.swing.JMenuItem Baixa_Lançamentos;
    private javax.swing.JMenuItem Cancela_Notas;
    private javax.swing.JMenuItem Cidade;
    private javax.swing.JMenuItem Cliente;
    private javax.swing.JMenu DAV;
    private javax.swing.JMenuItem Estado;
    private javax.swing.JMenuItem Fechamento_Caixa;
    private javax.swing.JMenuItem Filial;
    private javax.swing.JMenuItem Filial1;
    private javax.swing.JMenuItem Fornecedor;
    private javax.swing.JMenuItem Grupo_Fiscal;
    private javax.swing.JMenuItem Grupo_Fiscal1;
    private javax.swing.JMenuItem MVA;
    private javax.swing.JMenuItem MVA1;
    private javax.swing.JMenuItem MenuGrupo;
    private javax.swing.JMenuItem MenuNCMSH;
    private javax.swing.JMenu Menu_Boleto;
    private javax.swing.JMenu Menu_Cadastros;
    private javax.swing.JMenu Menu_Caixa;
    private javax.swing.JMenu Menu_Compras;
    private javax.swing.JMenu Menu_Config;
    private javax.swing.JMenu Menu_Config1;
    private javax.swing.JMenu Menu_Faturamento;
    private javax.swing.JMenu Menu_Financeiro;
    private javax.swing.JMenu Menu_Pessoa;
    private javax.swing.JMenuBar Menu_Principal;
    private javax.swing.JMenu Menu_Produtp;
    private javax.swing.JMenu Menu_Relatorios;
    private javax.swing.JMenuItem NCMSH;
    private javax.swing.JMenuItem NCMSH1;
    private javax.swing.JMenuItem Nota_Entrada;
    private javax.swing.JMenuItem Nota_Fiscal;
    private javax.swing.JMenuItem Ordem_de_Compras;
    private javax.swing.JMenuItem Orçamento;
    private javax.swing.JMenuItem Orçamento1;
    private javax.swing.JDesktopPane Panel_Principal;
    private javax.swing.JMenuItem Pedido;
    private javax.swing.JMenuItem Produto;
    private javax.swing.JMenuItem Regiao;
    private javax.swing.JMenuItem Relatorio_Cidades;
    private javax.swing.JMenuItem Relatorio_Compras;
    private javax.swing.JMenuItem Relatorio_Contas_Pagar;
    private javax.swing.JMenuItem Relatorio_Contas_Receber;
    private javax.swing.JMenu Relatorio_DAV;
    private javax.swing.JMenuItem Relatorio_Estados;
    private javax.swing.JMenuItem Relatorio_Fornecedores;
    private javax.swing.JMenu Relatorio_Notas;
    private javax.swing.JMenuItem Relatorio_Notas_Entrada;
    private javax.swing.JMenuItem Relatorio_Notas_Fiscais;
    private javax.swing.JMenuItem Relatorio_Orcamento;
    private javax.swing.JMenuItem Relatorio_Ordem_Serviço;
    private javax.swing.JMenuItem Relatorio_Pedidos;
    private javax.swing.JMenuItem Relatorio_Pre_Venda;
    private javax.swing.JMenu Relatorio_Produtos;
    private javax.swing.JMenuItem Relatorio_Produtos_Solicitados;
    private javax.swing.JMenuItem Relatorio_Produtos_Vendidos;
    private javax.swing.JMenuItem Relatorio_Região;
    private javax.swing.JMenuItem Relatorio_Transportadora;
    private javax.swing.JMenuItem Relatorio_Vendas;
    private javax.swing.JMenuItem Relatorio_Vendedores;
    private javax.swing.JMenuItem Relatorio_de_Comissões;
    private javax.swing.JMenuItem Relatorios_Curva_ABC;
    private javax.swing.JMenuItem Tipo_Notas;
    private javax.swing.JMenuItem Tipo_Notas1;
    private javax.swing.JMenuItem Transportadora;
    private javax.swing.JMenuItem Unidade_Medida;
    private javax.swing.JMenuItem Vendedor;
    private javax.swing.JMenuItem grupoFiscal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
