-- dados de acesso
--elephantsql
--email:gelvazio@gmail.com
--senha:453196

CREATE TABLE COND_PAG_SIMPLES(
    CD_COND INTEGER NOT NULL,
    DS_COND VARCHAR(50) NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL
);

CREATE TABLE COR(
    CD_COR INTEGER NOT NULL,
    DS_COR VARCHAR(50),
    DT_ALT DATE NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    HR_ALT TIME NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE ESTADO(
    CD_ESTADO VARCHAR(2) NOT NULL,
    DS_ESTADO VARCHAR(40) NOT NULL,
    CD_IBGE INTEGER,
    CD_FILIAL INTEGER NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL
);

CREATE TABLE ESTOQUE(
    CD_FILIAL INTEGER NOT NULL,
    CD_REF BIGINT NOT NULL,
    QT_PROD NUMERIC(18,4) NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_CAD DATE NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    HR_ALT TIME NOT NULL,
    DS_LOG_ESTOQUE VARCHAR(200),
    QT_COMPRA NUMERIC(16,4) DEFAULT 0 NOT NULL,
    QT_SOLICITADA NUMERIC(16,4) DEFAULT 0 NOT NULL
);

CREATE TABLE GRUPO(
    CD_GRUPO INTEGER NOT NULL,
    DS_GRUPO VARCHAR(50) NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    CD_GP_FISCAL_DEFAULT INTEGER,
    CD_NCM_SH_DEFAULT VARCHAR(20),
    VL_COMISSAO_GRUPO NUMERIC(16,4),
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE GRUPO_PESSOA(
    CD_GRUPO INTEGER NOT NULL,
    DS_GRUPO VARCHAR(60),
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    CD_TB_PRECO_ATIV INTEGER,
    CD_USUARIO SMALLINT NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE GRUPO_USUARIO(
    CD_GRUPO INTEGER NOT NULL,
    DS_GRUPO VARCHAR(50) NOT NULL,
    BL_PERMISSAO text,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    BL_PERMISSAO_CRY text,
    CD_FILIAL INTEGER NOT NULL);

CREATE TABLE ITENS_ORC_SIMPLES(
    CD_FILIAL SMALLINT NOT NULL,
    CD_MOVIMENTO INTEGER NOT NULL,
    CD_SEQ_ITE_PRO SMALLINT NOT NULL,
    CD_REFER_PRO BIGINT NOT NULL,
    QT_ITE_PRO NUMERIC(16,4) NOT NULL,
    VL_CUS_ITE_PRO NUMERIC(16,4),
    VL_VEN_ITE_PRO NUMERIC(16,4),
    DT_EMI_DOC DATE,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL
);

CREATE TABLE LANCAMENTOS(
    CD_FILIAL SMALLINT NOT NULL,
    CD_LANC INTEGER NOT NULL,
    DS_LANC VARCHAR(60),
    DT_LANC DATE,
    VL_VALOR NUMERIC(16,4),
    CD_USUARIO SMALLINT NOT NULL,
    DT_CAD DATE NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    HR_ALT TIME NOT NULL
);

CREATE TABLE MARCA(
    CD_MARCA INTEGER NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    DS_MARCA VARCHAR(50),
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE MUNICIPIO(
    CD_ESTADO VARCHAR(2) NOT NULL,
    CD_MUNICIPIO INTEGER NOT NULL,
    DS_MUNICIPIO VARCHAR(50) NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    CD_IBGE INTEGER,
    CD_CEP VARCHAR(20),
    CD_CODIGO_TOM VARCHAR(8),
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE ORCAMENTO_SIMPLES(
    CD_FILIAL SMALLINT NOT NULL,
    CD_MOVIMENTO INTEGER NOT NULL,
    CD_VENDE INTEGER,
    CD_PAGTO INTEGER,
    CD_PESSOA INTEGER,
    DT_EMI_DOC DATE,
    DT_SAI_DOC DATE,
    VL_TOT_CUS_DOC NUMERIC(16,4) DEFAULT 0 NOT NULL,
    VL_TOT_PRO_DOC NUMERIC(16,4) DEFAULT 0 NOT NULL,
    FG_SITUACAO SMALLINT,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL
);

CREATE TABLE PAIS(
    CD_PAIS INTEGER NOT NULL,
    NM_PAIS VARCHAR(100),
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE PARC_DOC(
    CD_FILIAL SMALLINT NOT NULL,
    CD_MOVIMENTO INTEGER NOT NULL,
    SQ_ITE_PAR SMALLINT NOT NULL,
    DT_VENCTO_PAR DATE NOT NULL,
    VL_PAR NUMERIC(16,4) NOT NULL,
    CD_DUPLICATA VARCHAR(35),
    CD_TIPO_COB_PAR NUMERIC(3),
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    DT_PAG_PAR DATE,
    VL_PAGO NUMERIC(16,4),
    FG_TIPO_CARTAO SMALLINT,
    NM_OPERADORA VARCHAR(50)
);

CREATE TABLE PARC_ORC(
    CD_FILIAL SMALLINT NOT NULL,
    CD_MOVIMENTO INTEGER NOT NULL,
    SQ_ITE_PAR SMALLINT NOT NULL,
    DT_VENCTO_PAR DATE NOT NULL,
    VL_PAR NUMERIC(16,4) NOT NULL,
    CD_TIPO_COB_PAR INTEGER,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    DT_PAG_PAR DATE,
    VL_PAGO NUMERIC(16,4),
    CD_DUPLICATA VARCHAR(35),
    FG_TIPO_CARTAO SMALLINT,
    NM_OPERADORA VARCHAR(50)
);

CREATE TABLE PARCELASENTRADA(
    CD_FILIAL SMALLINT NOT NULL,
    CD_MOV_ENT INTEGER NOT NULL,
    SQ_SEQUENCIA INTEGER NOT NULL,
    DT_VENCIMENTO DATE NOT NULL,
    VL_VALOR NUMERIC(16,4) NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    DT_PAG_PAR DATE,
    VL_PAGO NUMERIC(16,4),
    DT_PAGO DATE,
    VL_ACRESCIMO NUMERIC(16,4) DEFAULT 0,
    VL_DESCONTO NUMERIC(16,4) DEFAULT 0,
    FG_STATUS SMALLINT,
    CD_TIPO_COBR INTEGER
);

CREATE TABLE PESSOA_SIMPLES(
    CD_PESSOA INTEGER NOT NULL,
    NM_PESSOA VARCHAR(400) NOT NULL,
    DS_ENDERECO VARCHAR(400),
    NR_ENDERECO VARCHAR(50),
    DS_BAIRRO VARCHAR(200),
    CD_ESTADO VARCHAR(2),
    CD_CIDADE INTEGER,
    CD_PAIS INTEGER DEFAULT 1058,
    CD_CEP VARCHAR(8),
    DS_EMAIL VARCHAR(200),
    NR_TELEFONE VARCHAR(200),
    CD_CGCCPF VARCHAR(25) NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE PRODUTO_SIMPLES(
    CD_PROD INTEGER NOT NULL,
    DS_PROD VARCHAR(100) NOT NULL,
    CD_GRUPO INTEGER NOT NULL,
    CD_SUB_GRUPO INTEGER NOT NULL,
    FG_ATIVO SMALLINT DEFAULT 1,
    CD_COR INTEGER,
    CD_FABRICA VARCHAR(40),
    CD_MARCA INTEGER,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    CD_GP_FISCAL SMALLINT NOT NULL,
    CD_NCM_SH INTEGER,
    CD_REF BIGINT NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    CD_FILIAL INTEGER NOT NULL);

CREATE TABLE REGIAO(
    CD_REGIAO INTEGER NOT NULL,
    DS_REGIAO VARCHAR(60),
    CD_USUARIO SMALLINT NOT NULL,
    DT_CAD DATE NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    HR_ALT TIME NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE STATUS_PEDIDO(
    CD_STATUS INTEGER NOT NULL,
    DS_STATUS VARCHAR(40) NOT NULL,
    FG_BAIXA_ESTOQUE SMALLINT NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE SUB_COND_PAG(
    CD_COND INTEGER NOT NULL,
    CD_PAR SMALLINT NOT NULL,
    NR_DIAS_PAR SMALLINT NOT NULL,
    CD_COBR INTEGER,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    TX_OPER_TICK NUMERIC(16,4) DEFAULT 0 NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);


CREATE TABLE SUB_GRUPO(
    CD_GRUPO INTEGER NOT NULL,
    CD_SUB_GRUPO INTEGER NOT NULL,
    DS_SUB_GRUPO VARCHAR(35) NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    CD_NCM_SH_DEFAULT VARCHAR(20),
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE SUB_REGIAO(
    CD_REGIAO INTEGER NOT NULL,
    CD_ESTADO VARCHAR(2) NOT NULL,
    CD_MUNICIPIO INTEGER NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_CAD DATE NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    HR_ALT TIME NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE SUB_TAB_PRECO(
    CD_TABELA INTEGER NOT NULL,
    CD_REF BIGINT NOT NULL,
    VL_CUSTO NUMERIC(16,4),
    VL_VENDA NUMERIC(16,4),
    VL_PROMOCAO NUMERIC(16,4),
    VL_REVENDA NUMERIC(16,4),
    VL_TABELA NUMERIC(16,4),
    VL_CUSTO_MED NUMERIC(16,4),
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    VL_FABRICA NUMERIC(16,4),
    VL_ESPECIAL NUMERIC(16,4),
    VL_VAREJO NUMERIC(16,4),
    DT_ENTRADA DATE,
    DS_LOG VARCHAR(200),
    TX_MARGEM_LUCRO_VENDA NUMERIC(16,4),
    TX_MARGEM_LUCRO_REVENDA NUMERIC(16,4),
    TX_MARGEM_LUCRO_ESPECIAL NUMERIC(16,4),
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE SUB_TIPO_NOTA(
    CD_TIPO INTEGER NOT NULL,
    SQ_TIPO INTEGER NOT NULL,
    DS_DESCRICAO VARCHAR(100),
    CD_TAB_PRECO INTEGER NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE TAM(
    CD_TAM INTEGER NOT NULL,
    DS_TAM VARCHAR(20) NOT NULL,
    DT_CAD DATE NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    HR_ALT TIME NOT NULL,
    CD_USUARIO VARCHAR(20) NOT NULL,
    CD_FILIAL INTEGER NOT NULL);

CREATE TABLE TELAS(
    CD_FILIAL SMALLINT NOT NULL,
    DS_TELA VARCHAR(50) NOT NULL,
    FG_EM_USO SMALLINT,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL
);

CREATE TABLE TIPO_COBRANCA(
    CD_COBR INTEGER NOT NULL,
    DS_COBR VARCHAR(30) NOT NULL,
    FG_IMED SMALLINT DEFAULT 0,
    FG_GERADUPLI SMALLINT DEFAULT 0 NOT NULL,
    FG_CHEQUE SMALLINT DEFAULT 0 NOT NULL,
    FG_CARTAO SMALLINT DEFAULT 0 NOT NULL,
    FG_IMPRIME SMALLINT DEFAULT 0 NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    FG_CREDIARIO SMALLINT DEFAULT 0 NOT NULL,
    FG_GERA_BOLETO SMALLINT,
    FG_REDEADM SMALLINT,
    FG_REDEATIVA SMALLINT DEFAULT 0 NOT NULL,
    CD_CONTA_CREDITO INTEGER DEFAULT 0 NOT NULL,
    FG_PAGA_QNDO_GERA SMALLINT DEFAULT 0 NOT NULL,
    FG_LANCA_CCORRENTE_PESSOA SMALLINT DEFAULT 0 NOT NULL,
    FG_TICKET SMALLINT DEFAULT 0 NOT NULL,
    CD_OPERADORA INTEGER DEFAULT 0 NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE TIPO_LANCAMENTO(
    CD_TIPO INTEGER NOT NULL,
    DS_TIPO VARCHAR(25) NOT NULL,
    DT_CAD DATE NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    HR_ALT TIME NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    FG_DBCR SMALLINT,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE TIPO_NOTA_FISCAL(
    CD_TIPO SMALLINT NOT NULL,
    CD_GP_FISCAL SMALLINT NOT NULL,
    TP_CONSUMO SMALLINT NOT NULL,
    CD_CFOP_ESTADUAL SMALLINT,
    CD_CFOP_INTERESTADUAL SMALLINT,
    CD_CST SMALLINT,
    TP_CALCULO_BASE VARCHAR(200),
    TP_CALCULO_ICMS VARCHAR(200),
    TP_CALCULO_BASE_I VARCHAR(200),
    TP_CALCULO_ICMS_I VARCHAR(200),
    DS_OBS_NF TEXT,
    CD_USUARIO SMALLINT NOT NULL,
    DT_CAD DATE NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    HR_ALT TIME NOT NULL,
    CD_CST_IPI VARCHAR(2),
    CD_CST_PIS VARCHAR(2),
    CD_CST_COFINS VARCHAR(2),
    TP_CALCULO_BASE_ST VARCHAR(200),
    TP_CALCULO_ICMS_ST VARCHAR(200),
    TP_CALCULO_BASE_I_ST VARCHAR(200),
    TP_CALCULO_ICMS_I_ST VARCHAR(200),
    CD_INFO SMALLINT,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE TIPO_NOTA_SIMPLES(
    CD_TIPO INTEGER NOT NULL,
    DS_TIPO_NOTA VARCHAR(60) NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE TRANSP(
    CD_TRANS INTEGER NOT NULL,
    NM_TRANS VARCHAR(100) NOT NULL,
    DS_END_TRANS VARCHAR(100),
    DS_BAI_TRANS VARCHAR(50),
    CD_UF_TRANS VARCHAR(2),
    CD_CID_TRANS INTEGER,
    NR_CEP_TRANS VARCHAR(8),
    NR_CNPJ_TRANS VARCHAR(19),
    NR_INS_TRANS VARCHAR(20),
    DS_EMAIL_TRANS VARCHAR(70),
    TF_TRANS VARCHAR(20),
    CD_USUARIO SMALLINT NOT NULL,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    NR_END_TRANS VARCHAR(5),
    CD_COMPLEMENTO VARCHAR(40),
    TP_PESSOA SMALLINT,
    CD_FILIAL INTEGER NOT NULL);

CREATE TABLE UNIDADE_MEDIDA(
    CD_UNIDADE SMALLINT NOT NULL,
    DS_SIGLA VARCHAR(6),
    DS_UNIDADE VARCHAR(40),
    TX_FATOR NUMERIC(16,4) DEFAULT 1 NOT NULL,
    FG_VENDA_FRACIONARIA SMALLINT DEFAULT 1 NOT NULL,
    DT_ALT DATE NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL,
    HR_ALT TIME NOT NULL,
    CD_USUARIO SMALLINT NOT NULL,
    CD_FILIAL INTEGER NOT NULL
);

CREATE TABLE USUARIO(
    CD_USUARIO SMALLINT NOT NULL,
    DS_USUARIO VARCHAR(400) NOT NULL,
    DS_SENHA VARCHAR(10),
    CD_FILIAL INTEGER,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL
);

CREATE TABLE LOGSISTEMA(
    ID SERIAL NOT NULL,
    TABELA VARCHAR(400) NOT NULL,
    CHAVE JSONB NOT NULL DEFAULT '[]',
    CD_FILIAL INTEGER,
    DT_ALT DATE NOT NULL,
    HR_ALT TIME NOT NULL,
    DT_CAD DATE NOT NULL,
    HR_CAD TIME NOT NULL
);

    script
    ALTER TABLE cond_pag_simples OWNER TO 'public';GRANT ALL ON TABLE cond_pag_simples TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table cond_pag_simples TO 'public';GRANT SELECT ON TABLE  cond_pag_simples TO 'public';GRANT ALL ON TABLE  cond_pag_simples TO 'public';
    ALTER TABLE cor OWNER TO 'public';GRANT ALL ON TABLE cor TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table cor TO 'public';GRANT SELECT ON TABLE  cor TO 'public';GRANT ALL ON TABLE  cor TO 'public';
    ALTER TABLE estado OWNER TO 'public';GRANT ALL ON TABLE estado TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table estado TO 'public';GRANT SELECT ON TABLE  estado TO 'public';GRANT ALL ON TABLE  estado TO 'public';
    ALTER TABLE estoque OWNER TO 'public';GRANT ALL ON TABLE estoque TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table estoque TO 'public';GRANT SELECT ON TABLE  estoque TO 'public';GRANT ALL ON TABLE  estoque TO 'public';
    ALTER TABLE grupo OWNER TO 'public';GRANT ALL ON TABLE grupo TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table grupo TO 'public';GRANT SELECT ON TABLE  grupo TO 'public';GRANT ALL ON TABLE  grupo TO 'public';
    ALTER TABLE grupo_pessoa OWNER TO 'public';GRANT ALL ON TABLE grupo_pessoa TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table grupo_pessoa TO 'public';GRANT SELECT ON TABLE  grupo_pessoa TO 'public';GRANT ALL ON TABLE  grupo_pessoa TO 'public';
    ALTER TABLE grupo_usuario OWNER TO 'public';GRANT ALL ON TABLE grupo_usuario TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table grupo_usuario TO 'public';GRANT SELECT ON TABLE  grupo_usuario TO 'public';GRANT ALL ON TABLE  grupo_usuario TO 'public';
    ALTER TABLE itens_orc_simples OWNER TO 'public';GRANT ALL ON TABLE itens_orc_simples TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table itens_orc_simples TO 'public';GRANT SELECT ON TABLE  itens_orc_simples TO 'public';GRANT ALL ON TABLE  itens_orc_simples TO 'public';
    ALTER TABLE lancamentos OWNER TO 'public';GRANT ALL ON TABLE lancamentos TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table lancamentos TO 'public';GRANT SELECT ON TABLE  lancamentos TO 'public';GRANT ALL ON TABLE  lancamentos TO 'public';
    ALTER TABLE marca OWNER TO 'public';GRANT ALL ON TABLE marca TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table marca TO 'public';GRANT SELECT ON TABLE  marca TO 'public';GRANT ALL ON TABLE  marca TO 'public';
    ALTER TABLE municipio OWNER TO 'public';GRANT ALL ON TABLE municipio TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table municipio TO 'public';GRANT SELECT ON TABLE  municipio TO 'public';GRANT ALL ON TABLE  municipio TO 'public';
    ALTER TABLE orcamento_simples OWNER TO 'public';GRANT ALL ON TABLE orcamento_simples TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table orcamento_simples TO 'public';GRANT SELECT ON TABLE  orcamento_simples TO 'public';GRANT ALL ON TABLE  orcamento_simples TO 'public';
    ALTER TABLE pais OWNER TO 'public';GRANT ALL ON TABLE pais TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table pais TO 'public';GRANT SELECT ON TABLE  pais TO 'public';GRANT ALL ON TABLE  pais TO 'public';
    ALTER TABLE parc_doc OWNER TO 'public';GRANT ALL ON TABLE parc_doc TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table parc_doc TO 'public';GRANT SELECT ON TABLE  parc_doc TO 'public';GRANT ALL ON TABLE  parc_doc TO 'public';
    ALTER TABLE parc_orc OWNER TO 'public';GRANT ALL ON TABLE parc_orc TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table parc_orc TO 'public';GRANT SELECT ON TABLE  parc_orc TO 'public';GRANT ALL ON TABLE  parc_orc TO 'public';
    ALTER TABLE parcelasentrada OWNER TO 'public';GRANT ALL ON TABLE parcelasentrada TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table parcelasentrada TO 'public';GRANT SELECT ON TABLE  parcelasentrada TO 'public';GRANT ALL ON TABLE  parcelasentrada TO 'public';
    ALTER TABLE pessoa_simples OWNER TO 'public';GRANT ALL ON TABLE pessoa_simples TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table pessoa_simples TO 'public';GRANT SELECT ON TABLE  pessoa_simples TO 'public';GRANT ALL ON TABLE  pessoa_simples TO 'public';
    ALTER TABLE produto_simples OWNER TO 'public';GRANT ALL ON TABLE produto_simples TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table produto_simples TO 'public';GRANT SELECT ON TABLE  produto_simples TO 'public';GRANT ALL ON TABLE  produto_simples TO 'public';
    ALTER TABLE regiao OWNER TO 'public';GRANT ALL ON TABLE regiao TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table regiao TO 'public';GRANT SELECT ON TABLE  regiao TO 'public';GRANT ALL ON TABLE  regiao TO 'public';
    ALTER TABLE status_pedido OWNER TO 'public';GRANT ALL ON TABLE status_pedido TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table status_pedido TO 'public';GRANT SELECT ON TABLE  status_pedido TO 'public';GRANT ALL ON TABLE  status_pedido TO 'public';
    ALTER TABLE sub_cond_pag OWNER TO 'public';GRANT ALL ON TABLE sub_cond_pag TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table sub_cond_pag TO 'public';GRANT SELECT ON TABLE  sub_cond_pag TO 'public';GRANT ALL ON TABLE  sub_cond_pag TO 'public';
    ALTER TABLE sub_grupo OWNER TO 'public';GRANT ALL ON TABLE sub_grupo TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table sub_grupo TO 'public';GRANT SELECT ON TABLE  sub_grupo TO 'public';GRANT ALL ON TABLE  sub_grupo TO 'public';
    ALTER TABLE sub_regiao OWNER TO 'public';GRANT ALL ON TABLE sub_regiao TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table sub_regiao TO 'public';GRANT SELECT ON TABLE  sub_regiao TO 'public';GRANT ALL ON TABLE  sub_regiao TO 'public';
    ALTER TABLE sub_tipo_nota OWNER TO 'public';GRANT ALL ON TABLE sub_tipo_nota TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table sub_tipo_nota TO 'public';GRANT SELECT ON TABLE  sub_tipo_nota TO 'public';GRANT ALL ON TABLE  sub_tipo_nota TO 'public';
    ALTER TABLE tam OWNER TO 'public';GRANT ALL ON TABLE tam TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table tam TO 'public';GRANT SELECT ON TABLE  tam TO 'public';GRANT ALL ON TABLE  tam TO 'public';
    ALTER TABLE telas OWNER TO 'public';GRANT ALL ON TABLE telas TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table telas TO 'public';GRANT SELECT ON TABLE  telas TO 'public';GRANT ALL ON TABLE  telas TO 'public';
    ALTER TABLE tipo_cobranca OWNER TO 'public';GRANT ALL ON TABLE tipo_cobranca TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table tipo_cobranca TO 'public';GRANT SELECT ON TABLE  tipo_cobranca TO 'public';GRANT ALL ON TABLE  tipo_cobranca TO 'public';
    ALTER TABLE tipo_lancamento OWNER TO 'public';GRANT ALL ON TABLE tipo_lancamento TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table tipo_lancamento TO 'public';GRANT SELECT ON TABLE  tipo_lancamento TO 'public';GRANT ALL ON TABLE  tipo_lancamento TO 'public';
    ALTER TABLE tipo_nota_fiscal OWNER TO 'public';GRANT ALL ON TABLE tipo_nota_fiscal TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table tipo_nota_fiscal TO 'public';GRANT SELECT ON TABLE  tipo_nota_fiscal TO 'public';GRANT ALL ON TABLE  tipo_nota_fiscal TO 'public';
    ALTER TABLE tipo_nota_simples OWNER TO 'public';GRANT ALL ON TABLE tipo_nota_simples TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table tipo_nota_simples TO 'public';GRANT SELECT ON TABLE  tipo_nota_simples TO 'public';GRANT ALL ON TABLE  tipo_nota_simples TO 'public';
    ALTER TABLE transp OWNER TO 'public';GRANT ALL ON TABLE transp TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table transp TO 'public';GRANT SELECT ON TABLE  transp TO 'public';GRANT ALL ON TABLE  transp TO 'public';
    ALTER TABLE unidade_medida OWNER TO 'public';GRANT ALL ON TABLE unidade_medida TO 'public';GRANT INSERT, SELECT, UPDATE, DELETE ON table unidade_medida TO 'public';GRANT SELECT ON TABLE  unidade_medida TO 'public';GRANT ALL ON TABLE  unidade_medida TO 'public';
    ALTER TABLE usuario OWNER TO 'public';

    GRANT ALL ON TABLE usuario TO "comdvayv";

    GRANT INSERT, SELECT, UPDATE, DELETE ON table usuario TO 'public';GRANT SELECT ON TABLE  usuario TO 'public';GRANT ALL ON TABLE  usuario TO 'public';

