package sistema.sistema_java_ok.src.principal;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gelvazio Camargo
 */
public class consultaVendas extends javax.swing.JDialog {

    /**
     * Creates new form consultaVendas
     */
    public consultaVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        ven.setListaVend(ven.retornaVendas());
        for (int f = 0; f < ven.getListaVend().size(); f++) {
            String[] linhaResul;
            linhaResul = ven.getListaVend().get(f).split(";");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            cli.setCodigo(Integer.parseInt(linhaResul[1]));
            cli.procurarCliente();
            vend.setCodigo(Integer.parseInt(linhaResul[2]));
            vend.procurarVendedor();
            Object[] linha = {linhaResul[0], cli.getNome(), vend.getNome()};
            model.addRow(linha);
        }
    }
    public int codigo;
    Venda ven = new Venda();
    Vendedor vend = new Vendedor();
    Cliente cli = new Cliente();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        RadioButtonTodos = new javax.swing.JRadioButton();
        RadioButtonCodigo = new javax.swing.JRadioButton();
        RadioButtonCliente = new javax.swing.JRadioButton();
        RadioButtonVendedor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 580, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consulta de Vendas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 620, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "Vendedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 600, 340));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 580, -1));

        RadioButtonTodos.setSelected(true);
        RadioButtonTodos.setText("Todos");
        RadioButtonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonTodosActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButtonTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        RadioButtonCodigo.setText("Código");
        RadioButtonCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButtonCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        RadioButtonCliente.setText("Cliente");
        RadioButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonClienteActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButtonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        RadioButtonVendedor.setText("Vendedor");
        RadioButtonVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButtonVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        codigo = Integer.parseInt(String.valueOf(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0)));
        dispose();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows(0);
            ven.setListaVend(ven.retornaVendas());
            
            if (RadioButtonTodos.isSelected()) { //Todos
                for (int f = 0; f < ven.getListaVend().size(); f++) {
                    String[] linhaResul;
                    linhaResul = ven.getListaVend().get(f).split(";");
                    cli.setCodigo(Integer.parseInt(linhaResul[1]));
                    cli.procurarCliente();
                    vend.setCodigo(Integer.parseInt(linhaResul[2]));
                    vend.procurarVendedor();
                    Object[] linha = {linhaResul[0], cli.getNome(), vend.getNome()};
                    model.addRow(linha);
                }
            } else if (RadioButtonCodigo.isSelected()) { //Código
                for (int f = 0; f < ven.getListaVend().size(); f++) {
                    String[] linhaResul;
                    linhaResul = ven.getListaVend().get(f).split(";");
                    if (linhaResul[0].equals(jTextField1.getText())) {
                        Object[] linha = {linhaResul[0], cli.getNome(), vend.getNome()};
                        model.addRow(linha);
                    }
                }
            } else if (RadioButtonCliente.isSelected()) { //Cliente
                for (int f = 0; f < ven.getListaVend().size(); f++) {
                    String[] linhaResul;
                    linhaResul = ven.getListaVend().get(f).split(";");
                    cli.setCodigo(Integer.parseInt(linhaResul[1]));
                    cli.procurarCliente();
                    vend.setCodigo(Integer.parseInt(linhaResul[2]));
                    vend.procurarVendedor();
                    String nome = cli.getNome().toUpperCase();
                    String digitado = jTextField1.getText().toUpperCase();
                    if (nome.contains(digitado)) {
                        Object[] linha = {linhaResul[0], cli.getNome(), vend.getNome()};
                        model.addRow(linha);
                    }
                }
            } else if (RadioButtonVendedor.isSelected()) { //Vendedor
                for (int f = 0; f < ven.getListaVend().size(); f++) {
                    String[] linhaResul;
                    linhaResul = ven.getListaVend().get(f).split(";");
                    cli.setCodigo(Integer.parseInt(linhaResul[1]));
                    cli.procurarCliente();
                    vend.setCodigo(Integer.parseInt(linhaResul[2]));
                    vend.procurarVendedor();
                    String nome = vend.getNome().toUpperCase();
                    String digitado = jTextField1.getText().toUpperCase();
                    if (nome.contains(digitado)) {
                        Object[] linha = {linhaResul[0], cli.getNome(), vend.getNome()};
                        model.addRow(linha);
                    }
                }
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void RadioButtonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonTodosActionPerformed
        if (RadioButtonTodos.isSelected()) {
            RadioButtonCodigo.setSelected(false);
            RadioButtonCliente.setSelected(false);
            RadioButtonVendedor.setSelected(false);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setNumRows(0);
            ven.setListaVend(ven.retornaVendas());
            for (int f = 0; f < ven.getListaVend().size(); f++) {
                String[] linhaResul;
                linhaResul = ven.getListaVend().get(f).split(";");
                cli.setCodigo(Integer.parseInt(linhaResul[1]));
                cli.procurarCliente();
                vend.setCodigo(Integer.parseInt(linhaResul[2]));
                vend.procurarVendedor();
                Object[] linha = {linhaResul[0], cli.getNome(), vend.getNome()};
                model.addRow(linha);
            }
        } else {
            RadioButtonCliente.setSelected(true);
        }
        jTextField1.requestFocus();
        jTextField1.selectAll();
    }//GEN-LAST:event_RadioButtonTodosActionPerformed

    private void RadioButtonCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonCodigoActionPerformed
        if (RadioButtonCodigo.isSelected()) {
            RadioButtonTodos.setSelected(false);
            RadioButtonCliente.setSelected(false);
            RadioButtonVendedor.setSelected(false);
        } else {
            RadioButtonTodos.setSelected(true);
        }
        jTextField1.requestFocus();
        jTextField1.selectAll();
    }//GEN-LAST:event_RadioButtonCodigoActionPerformed

    private void RadioButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonClienteActionPerformed
        if (RadioButtonCliente.isSelected()) {
            RadioButtonTodos.setSelected(false);
            RadioButtonCodigo.setSelected(false);
            RadioButtonVendedor.setSelected(false);
        } else {
            RadioButtonCodigo.setSelected(true);
        }
        jTextField1.requestFocus();
        jTextField1.selectAll();
    }//GEN-LAST:event_RadioButtonClienteActionPerformed

    private void RadioButtonVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonVendedorActionPerformed
        if (RadioButtonCliente.isSelected()) {
            RadioButtonTodos.setSelected(false);
            RadioButtonCodigo.setSelected(false);
            RadioButtonCliente.setSelected(false);
        } else {
            RadioButtonCodigo.setSelected(true);
        }
        jTextField1.requestFocus();
        jTextField1.selectAll();
    }//GEN-LAST:event_RadioButtonVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                consultaVendas dialog = new consultaVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioButtonCliente;
    private javax.swing.JRadioButton RadioButtonCodigo;
    private javax.swing.JRadioButton RadioButtonTodos;
    private javax.swing.JRadioButton RadioButtonVendedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
